# Copyright 2017 Diamond Light Source
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific
# language governing permissions and limitations under the License.


name: CI

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - README.md
      - README.template
      - .github/workflows/readme.yml
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - README.md
      - README.template
      - .github/workflows/readme.yml

  workflow_dispatch:

jobs:
  build_env:
    name: Build Docker Env Image
    runs-on: ubuntu-20.04

    outputs:
      docker_env_repo_tag: ${{ steps.output_docker_env_repo_tag.outputs.docker_env_repo_tag }}

    steps:
      # Configure environment variable depending on which branch we are running on
      - name: Set env to master
        if: endsWith(github.ref, '/master')
        run: echo "DOCKER_REPO_TAG=opt-id:env" >> $GITHUB_ENV
      - name: Set env to branch
        if: (!endsWith(github.ref, '/master'))
        run: echo "DOCKER_REPO_TAG=opt-id:env-${GITHUB_REF##*/}" >> $GITHUB_ENV
      - id: output_docker_env_repo_tag
        run: echo "::set-output name=docker_env_repo_tag::$DOCKER_REPO_TAG"

      # Checks-out repository under $(pwd)
      - uses: actions/checkout@v2

      # Build Docker image, push image to Dockerhub on success
      - name: Pull existing Docker image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/$DOCKER_REPO_TAG || true

      - name: Build Docker image
        run: |
          docker build --pull --cache-from ${{ secrets.DOCKER_USERNAME }}/$DOCKER_REPO_TAG --tag ${{ secrets.DOCKER_USERNAME }}/$DOCKER_REPO_TAG -f env.Dockerfile .

      - name: Push Docker image to Dockerhub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/$DOCKER_REPO_TAG

  test_env:
    name: Executes Tests on Docker Env Image
    runs-on: ubuntu-20.04

    needs: build_env

    steps:
      # Checks-out repository under $(pwd)
      - uses: actions/checkout@v2

      # Execute tests
      - name: Pull existing Docker image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/${{ needs.build_env.outputs.docker_env_repo_tag }}

      - name: Start container
        run: |
          docker run -itd --name env -v $(pwd):/tmp/repo/ -w /tmp/repo/ ${{ secrets.DOCKER_USERNAME }}/${{ needs.build_env.outputs.docker_env_repo_tag }}

      - name: Install repo within container
        run: |
          docker exec env pip install -e .

      - name: Execute tests within container
        run: |
          docker exec env python -m pytest --cov=src tests/ --cov-report xml:coverage.xml --cov-report term-missing

      - name: Submit coverage to Codecov
        run: |
          bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }} -f coverage.xml

      - name: Halt container
        run: docker stop env

  build_image:
    name: Build Docker Image
    runs-on: ubuntu-20.04

    needs:
      - build_env
      - test_env

    outputs:
      docker_repo_tag: ${{ steps.output_docker_repo_tag.outputs.docker_repo_tag }}

    steps:
      # Configure environment variable depending on which branch we are running on
      - name: Set env to master
        if: endsWith(github.ref, '/master')
        run: echo "DOCKER_REPO_TAG=opt-id:latest" >> $GITHUB_ENV
      - name: Set env to branch
        if: (!endsWith(github.ref, '/master'))
        run: echo "DOCKER_REPO_TAG=opt-id:${GITHUB_REF##*/}" >> $GITHUB_ENV
      - id: output_docker_repo_tag
        run: echo "::set-output name=docker_repo_tag::$DOCKER_REPO_TAG"

      # Checks-out repository under $(pwd)
      - uses: actions/checkout@v2

      # Build Docker image, push image to Dockerhub on success
      - name: Pull existing Docker image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/$DOCKER_REPO_TAG || true

      - name: Build Docker image
        run: |
          docker build --build-arg BASE="${{ secrets.DOCKER_USERNAME }}/${{ needs.build_env.outputs.docker_env_repo_tag }}" --pull --cache-from ${{ secrets.DOCKER_USERNAME }}/$DOCKER_REPO_TAG --tag ${{ secrets.DOCKER_USERNAME }}/$DOCKER_REPO_TAG -f Dockerfile .

      - name: Start container
        run: |
          docker run -itd --name env ${{ secrets.DOCKER_USERNAME }}/$DOCKER_REPO_TAG

      - name: Execute tests within container
        run: |
          docker exec env python -m pytest --cov=/usr/local/Opt-ID/src /usr/local/Opt-ID/tests/ --cov-report term-missing

      - name: Halt container
        run: docker stop env

      - name: Push Docker image to Dockerhub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/$DOCKER_REPO_TAG
